### ISSUE TITLE
ImportError: No modul named builtins

### ISSUE THREAD

**Issue by Braggo** [noobscode/kalel#8]
if i want to run kalel, an error occurs:

Traceback (most recent call last):
  File "kalel", line 7, in <module>
    from builtins import input
ImportError: No module named builtins

How can i fix it?

python --version: Python 2.7.17

**Comment by Braggo** [comment]
i have fixed it. But now i have error:

Do you agree to the terms of service [y/n]:  
Traceback (most recent call last):
  File "kalel", line 361, in <module>
    mainmenu()
  File "kalel", line 191, in mainmenu
    agreement()
  File "kalel", line 154, in agreement
    choice = input("\nDo you agree to the terms of service [y/n]: ")
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
